import Foundation

public struct PasteboardTypePolicy: Sendable {
    public init() {}

    public func evaluate(types: [String]) -> CaptureDecision {
        let normalized = types.map { $0.lowercased() }
        if normalized.contains(where: { $0.contains("transienttype") || $0.contains("transient") }) {
            return .ignore(.transientType)
        }
        if normalized.contains(where: { $0.contains("concealedtype") || $0.contains("concealed") }) {
            return .ignore(.concealedType)
        }
        if normalized.contains(where: { $0.contains("autogeneratedtype") || $0.contains("autogenerated") }) {
            return .ignore(.autoGeneratedType)
        }
        return .allow
    }
}

public struct IgnoredAppStore: Equatable, Sendable {
    public static let recommendedIgnoredBundleIDs: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.dashlane.dashlane",
        "com.lastpass.LastPass",
        "com.yubico.yubioath",
        "com.apple.keychainaccess",
    ]

    public private(set) var ignoredBundleIdentifiers: Set<String>

    public init(defaultIgnoredBundleIDs: Set<String> = recommendedIgnoredBundleIDs) {
        ignoredBundleIdentifiers = defaultIgnoredBundleIDs
    }

    public init(defaultIgnoredBundleIDs: [String]) {
        self.init(defaultIgnoredBundleIDs: Set(defaultIgnoredBundleIDs))
    }

    public func isIgnored(bundleIdentifier: String?) -> Bool {
        guard let bundleIdentifier else { return false }
        return ignoredBundleIdentifiers.contains(bundleIdentifier)
    }

    public mutating func setIgnored(_ ignored: Bool, bundleIdentifier: String) {
        if ignored {
            ignoredBundleIdentifiers.insert(bundleIdentifier)
        } else {
            ignoredBundleIdentifiers.remove(bundleIdentifier)
        }
    }
}

public struct SensitiveTextDetector: Sendable {
    public init() {}

    public func containsSensitiveText(_ text: String) -> Bool {
        containsPrivateKey(text)
            || containsSecretAssignment(text)
            || containsCommonTokenPrefix(text)
            || containsBearerToken(text)
            || containsJSONWebToken(text)
            || containsOTP(text)
            || containsCreditCard(text)
            || containsHighEntropyToken(text)
    }

    private func containsPrivateKey(_ text: String) -> Bool {
        text.range(of: #"-----BEGIN [A-Z ]*PRIVATE KEY-----"#, options: .regularExpression) != nil
    }

    private func containsSecretAssignment(_ text: String) -> Bool {
        text.range(
            of: #"(?i)\b(api[_-]?key|secret|token|password|passwd|access[_-]?key)\b\s*[:=]\s*['"]?[A-Za-z0-9_\-]{12,}"#,
            options: .regularExpression,
        ) != nil
    }

    private func containsCommonTokenPrefix(_ text: String) -> Bool {
        text.range(
            of: #"(?i)\b(ghp|gho|ghu|ghs|github_pat|glpat|sk_live|sk_test|xoxb|xoxp|xoxa|AKIA|ASIA)[A-Za-z0-9_\-]{12,}\b"#,
            options: .regularExpression,
        ) != nil
    }

    private func containsBearerToken(_ text: String) -> Bool {
        text.range(
            of: #"(?i)\bauthorization\s*:\s*bearer\s+[A-Za-z0-9_\-.=]{20,}"#,
            options: .regularExpression,
        ) != nil
    }

    private func containsJSONWebToken(_ text: String) -> Bool {
        text.range(
            of: #"\beyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}\b"#,
            options: .regularExpression,
        ) != nil
    }

    private func containsOTP(_ text: String) -> Bool {
        text.range(
            of: #"(?i)\b(otp|2fa|mfa|verification code|验证码|动态码|一次性密码)\b.{0,24}\b\d{4,8}\b"#,
            options: .regularExpression,
        ) != nil
    }

    private func containsCreditCard(_ text: String) -> Bool {
        let matches = text.matches(of: #"(?:\d[ -]?){13,19}"#)
        return matches.contains { candidate in
            let digits = candidate.filter(\.isNumber)
            return (13 ... 19).contains(digits.count) && luhnValid(digits)
        }
    }

    private func containsHighEntropyToken(_ text: String) -> Bool {
        let matches = text.matches(of: #"\b[A-Za-z0-9_\-]{40,}\b"#)
        return matches.contains { shannonEntropy($0) >= 4.0 }
    }

    private func luhnValid(_ digits: String) -> Bool {
        let values = digits.compactMap(\.wholeNumberValue)
        var sum = 0
        var doubleDigit = false
        for value in values.reversed() {
            var current = value
            if doubleDigit {
                current *= 2
                if current > 9 { current -= 9 }
            }
            sum += current
            doubleDigit.toggle()
        }
        return sum % 10 == 0
    }

    private func shannonEntropy(_ value: String) -> Double {
        guard !value.isEmpty else { return 0 }
        let counts = Dictionary(grouping: value, by: { $0 }).mapValues(\.count)
        let length = Double(value.count)
        return counts.values.reduce(0) { partial, count in
            let probability = Double(count) / length
            return partial - probability * log2(probability)
        }
    }
}

public struct PrivacyRuleEngine: Sendable {
    public var typePolicy: PasteboardTypePolicy
    public var ignoredAppStore: IgnoredAppStore
    public var sensitiveTextDetector: SensitiveTextDetector
    public var maxAllowedBytes: Int

    public init(
        typePolicy: PasteboardTypePolicy = PasteboardTypePolicy(),
        ignoredAppStore: IgnoredAppStore = IgnoredAppStore(),
        sensitiveTextDetector: SensitiveTextDetector = SensitiveTextDetector(),
        maxAllowedBytes: Int = 10 * 1024 * 1024,
    ) {
        self.typePolicy = typePolicy
        self.ignoredAppStore = ignoredAppStore
        self.sensitiveTextDetector = sensitiveTextDetector
        self.maxAllowedBytes = maxAllowedBytes
    }

    public func evaluate(snapshot: ClipboardSnapshot, settings: UserSettings) -> CaptureDecision {
        if settings.recordingPaused {
            return .ignore(.recordingPaused)
        }
        if ignoredAppStore.isIgnored(bundleIdentifier: snapshot.sourceApp?.bundleIdentifier)
            || settings.ignoredBundleIdentifiers.contains(snapshot.sourceApp?.bundleIdentifier ?? "")
        {
            return .ignore(.ignoredApplication)
        }
        let typeDecision = typePolicy.evaluate(types: snapshot.declaredTypes)
        if !typeDecision.isAllowed {
            return typeDecision
        }
        if snapshot.estimatedByteSize > maxAllowedBytes {
            return .ignore(.oversizedContent)
        }
        if settings.ignoreSensitiveContent,
           let preview = snapshot.previewText,
           sensitiveTextDetector.containsSensitiveText(preview)
        {
            return .ignore(.sensitiveContent)
        }
        return .allow
    }
}

private extension String {
    func matches(of pattern: String) -> [String] {
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
        let range = NSRange(startIndex ..< endIndex, in: self)
        return regex.matches(in: self, range: range).compactMap { match in
            Range(match.range, in: self).map { String(self[$0]) }
        }
    }
}
