@testable import ClipDockCore
import XCTest

final class PrivacyTests: XCTestCase {
    func testPasteboardTypePolicyIgnoresProtectedTypes() {
        let policy = PasteboardTypePolicy()

        XCTAssertEqual(policy.evaluate(types: ["org.nspasteboard.TransientType"]).reason, .transientType)
        XCTAssertEqual(policy.evaluate(types: ["org.nspasteboard.ConcealedType"]).reason, .concealedType)
        XCTAssertEqual(policy.evaluate(types: ["org.nspasteboard.AutoGeneratedType"]).reason, .autoGeneratedType)
        XCTAssertTrue(policy.evaluate(types: ["public.utf8-plain-text"]).isAllowed)
    }

    func testIgnoredAppStoreAllowsAndIgnoresBundleIdentifiers() {
        var store = IgnoredAppStore(defaultIgnoredBundleIDs: ["com.example.Secret"])

        XCTAssertTrue(store.isIgnored(bundleIdentifier: "com.example.Secret"))
        XCTAssertFalse(store.isIgnored(bundleIdentifier: "com.apple.Safari"))

        store.setIgnored(true, bundleIdentifier: "com.apple.Safari")
        XCTAssertTrue(store.isIgnored(bundleIdentifier: "com.apple.Safari"))
    }

    func testSensitiveTextDetectorFindsSecretsAndAvoidsCommonText() {
        let detector = SensitiveTextDetector()

        XCTAssertTrue(detector.containsSensitiveText("-----BEGIN PRIVATE KEY-----\nabc\n-----END PRIVATE KEY-----"))
        XCTAssertTrue(detector.containsSensitiveText("api_key = sk_live_1234567890abcdef"))
        XCTAssertTrue(detector.containsSensitiveText("ghp_1234567890abcdefghijklmnop"))
        XCTAssertTrue(detector.containsSensitiveText("Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.payload.signature"))
        XCTAssertTrue(detector.containsSensitiveText("Use OTP code 123456 to sign in"))
        XCTAssertTrue(detector.containsSensitiveText("4111 1111 1111 1111"))
        XCTAssertFalse(detector.containsSensitiveText("ClipDock saves clipboard history locally."))
    }

    func testPrivacyRuleEngineCoversDecisionPaths() {
        let detector = SensitiveTextDetector()
        let typePolicy = PasteboardTypePolicy()
        let ignoredApps = IgnoredAppStore(defaultIgnoredBundleIDs: ["com.example.Secret"])
        let engine = PrivacyRuleEngine(
            typePolicy: typePolicy,
            ignoredAppStore: ignoredApps,
            sensitiveTextDetector: detector,
        )

        var settings = UserSettings.defaults
        settings.recordingPaused = true
        XCTAssertEqual(engine.evaluate(snapshot: .text("hello"), settings: settings).reason, .recordingPaused)

        settings.recordingPaused = false
        let ignored = ClipboardSnapshot(
            declaredTypes: ["public.utf8-plain-text"],
            sourceApp: SourceAppMetadata(name: "Secret", bundleIdentifier: "com.example.Secret"),
            estimatedByteSize: 5,
            previewText: "hello",
        )
        XCTAssertEqual(engine.evaluate(snapshot: ignored, settings: settings).reason, .ignoredApplication)

        let sensitive = ClipboardSnapshot.text("secret = supersecretvalue12345")
        XCTAssertEqual(engine.evaluate(snapshot: sensitive, settings: settings).reason, .sensitiveContent)

        let transient = ClipboardSnapshot(declaredTypes: ["org.nspasteboard.TransientType"])
        XCTAssertEqual(engine.evaluate(snapshot: transient, settings: settings).reason, .transientType)

        let oversized = ClipboardSnapshot(
            declaredTypes: ["public.utf8-plain-text"],
            estimatedByteSize: 20 * 1024 * 1024,
            previewText: nil,
        )
        XCTAssertEqual(engine.evaluate(snapshot: oversized, settings: settings).reason, .oversizedContent)

        XCTAssertTrue(engine.evaluate(snapshot: .text("ordinary text"), settings: settings).isAllowed)
    }
}
